# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_comarca_cod_ibge'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensor',
            name='setor',
            field=models.CharField(default='Teresina', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feriado',
            name='descricao',
            field=models.CharField(default='Feriado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feriado',
            name='tipo',
            field=models.CharField(default='Feriado Nacional', max_length=30),
            preserve_default=False,
        ),
    ]
