# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0003_auto_20181011_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('defensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteio.Defensor')),
            ],
        ),
    ]
