# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0004_sorteio'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensor',
            name='afastamento_final',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defensor',
            name='afastamento_inicial',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
