# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0005_auto_20181030_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('defensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorteio.Defensor')),
            ],
        ),
    ]
