# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0006_afastamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensor',
            name='afastamento_final',
        ),
        migrations.RemoveField(
            model_name='defensor',
            name='afastamento_inicial',
        ),
    ]
