# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0007_auto_20181106_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='impedidos',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
