# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0008_feriado_impedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensor',
            name='recesso',
            field=models.BooleanField(default=False),
        ),
    ]
