# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0009_defensor_recesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensor',
            name='restricao',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
