# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-10-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0011_remove_defensor_restricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='defensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='sorteio.Defensor'),
        ),
    ]
