# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-10-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0012_auto_20191011_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='comarca',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='defensor',
            name='comarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defensores', to='sorteio.Comarca'),
        ),
    ]
