# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-10-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0013_auto_20211014_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='incluir_sorteio',
            field=models.BooleanField(default=False),
        ),
    ]
